name: Release falco_plugin (OCI)

on:
  release:
    types: [published]

permissions:
  contents: read # Default token to read


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: harden runner
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - name: install cosign
        uses: sigstore/cosign-installer@faadad0cce49287aee09b3a48701e75088a2c6ad # v4.0.0

      - name: checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v4
        with:
          persist-credentials: false

      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 #v3.6

      - name: docker setup buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3

      - name: docker login ghcr.io
        if: github.event_name != 'pull_request'
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3
        with:
          registry: ghcr.io
          username: "${{ github.actor }}"
          password: '${{ github.token }}'

      - name: extract metadata
        id: meta
        working-directory: ${{ env.CONTAINERFILE_DIR }}
        run: |
          REPO_NAME=${{ github.event.repository.name }}
          FULL_IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/edera_falco_plugin
          echo "full-image-name=${FULL_IMAGE_NAME,,}" >> $GITHUB_OUTPUT

          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            TAGS="${FULL_IMAGE_NAME,,}:pr-${{ github.event.number }}"
          else
            TAGS="${FULL_IMAGE_NAME,,}:${{ github.sha }},${FULL_IMAGE_NAME,,}:latest"
          fi
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT

      - name: build and push Docker image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        id: push
        with:
          context: .
          file: ./Containerfile
          platforms: "linux/amd64,linux/arm64"
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          labels: |
            org.opencontainers.image.title=${{ steps.meta.outputs.target-name }}
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: cosign all images
        if: github.event_name != 'pull_request'
        shell: bash
        run: |
          IFS=',' read -ra TAGS <<< '${{ steps.meta.outputs.tags }}'
          for tag in "${TAGS[@]}"; do
            pullstring="${tag}@${{ steps.push.outputs.digest }}"
            echo "Signing ${pullstring}"
            cosign sign --yes "${pullstring}"
          done
        env:
          DIGEST: '${{ steps.push.outputs.digest }}'
          COSIGN_EXPERIMENTAL: 'true'
